name: Deploy to deta

on: 
  push:
   branches-ignore:
    - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ready for deploying...
        run: echo Ready for deploying...

      - name: Deta Space Deployment Github Action
        uses: neobrains/space-deployment-github-action@v0.5
        with:
          # Deta access token for Deta Space CLI authentication.
          access_token: ${{ secrets.DETA_ACCESS_TOKEN }}
          # Deta Space app project ID.
          project_id: ${{ secrets.DETA_PROJECT_ID }}
          # Whether to do space push. Valid value is "true". Space push will not be performed by default.
          space_push: true

      - name: Deployed!
        run: echo Deployed!
